apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: demo-app
  labels:
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
      type: db
  template:
    metadata:
      labels:
        app: demo-app
        type: db
    spec:
      containers:
        - name: postgres
          image: postgres:alpine
          env:
            - name: POSTGRES_USER
              value: demo
            - name: POSTGRES_PASSWORD
              value: demo
          volumeMounts:
            - mountPath: /var/lib/postgres/data
              name: postgres-pv-data
          ports:
            - containerPort: 5432
      volumes:
        - name: postgres-pv-data
          persistentVolumeClaim:
            claimName: postgres-pv-claim
