apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.website.service.name }}
  namespace: demo-app
  labels:
    app: demo-app
spec:
  selector:
    app: demo-app
    type: website
  ports:
    - port: 9301
      targetPort: 9301
