apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume
  namespace: {{ .Values.namespace }}
  labels:
    app: demo-app
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.database.volume.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.database.volume.path }}
