{{- if .Values.database.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: demo-app
spec:
  selector:
    app: demo-app
    type: db
  ports:
    - port: {{ .Values.database.port }}
      targetPort: {{ .Values.database.port }}
{{- end }}
